- hosts: sandy
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: yes
  tasks:
  - name: find file
    find: paths="/var/www/html/" patterns='*.html' recurse=yes
    register: result
  - debug: var=result
