- hosts: sandy
  user: ubuntu
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: run the looop
      user: name={{ item }} state=present
      with_items:
        - user1
        - sandeep
        - veer
