---
- hosts: sandy
  user: ubuntu
  become_method: yes
  sudo: yes
  gather_facts: no
  tasks:
  - name: apache2
    apt: pkg=apache2 state=latest
  - name: date
    raw: /bin/date > /home/ubuntu/test/playbook_start.log
  - name: service check
    service: name=apache2 state=restarted
  - name: veriy statis
    command: service apache2 status
  - name: install telnet 
    apt: pkg=telnet state=latest
  - name: log all packages
    raw: apt list installed > /home/ubuntu/test/installed.log
  - name: date
    raw: /bin/date > /home/ubuntu/test/play_end.log
