- hosts: sandy
  user: ubuntu
  sudo: yes
  connection: ssh
  gather_facts: yes
  vars: 
    userName: usandntu
    userPassword: password123
    connectionType: SFTP
  tasks:
    - name: Install the tasks
      template: src=test.conf.j2 dest=/home/ubuntu/test/test.conf
