- hosts: '{{ myhosts }}'
  remote_user: ubuntu
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: '{{ gather }}'
  vars:
    myhosts: sandy
    gather: yes
    pkg: tree
  tasks:
  - name: install tree
    apt: 
      name: '{{ pkg }}'
      state: latest
