- hosts: all
  user: ubuntu
  become_method: yes
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: get the docker
    apt: pkg=docker.io state=latest
    register: result
  - debug: var=result

  - name: add the daemon.json file
    become: true
    copy:
      src: daemon.json
      dest: /etc/docker/daemon.json

  - name: add the kubernetes key
    apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg state=present
    register: result
  - debug: var=result

  - name: add the kubernetes.list file
    copy:  
      content: deb http://apt.kubernetes.io/ kubernetes-xenial main
      dest: /etc/apt/sources.list.d/kubernetes.list
 
  - name: status start
    service: name=docker state=restarted

  - name: install kubernetes softwares
    apt: pkg=kubelet,kubectl,kubeadm state=present

  - name: pull image maa
    command: sudo docker pull centos
    register: result
  - debug: var=result

  - name: spinning the cont
    command: sudo docker run -d --name "cont" centos tail -f /dev/null
    register: result
  - debug: var=result

