- hosts: all
  user: ubuntu
  become_method: yes
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
  - name: add the docker key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg state=present
    register: result
  - debug: var=result

  - name: adding docker repo
    apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable' state=present
    register: result
  - debug: var=result

  - name: get the docker
    apt: pkg=docker.io state=latest
    register: result
  - debug: var=result

  - name: status start
    service: name=docker state=restarted

  - name: pull image maa
    command: sudo docker pull centos
    register: result
  - debug: var=result

  - name: spinning the cont
    command: sudo docker run -d --name "cont" centos tail -f /dev/null
    register: result
  - debug: var=result

